# Generated by Django 5.0.1 on 2024-02-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_balance_alter_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan'),
        ),
    ]
